version: '3'
services:
  # Specify three fdbserver processes.
  fdb-coordinator:
    image: foundationdb:6.1.12
    environment:
      FDB_COORDINATOR: fdb-coordinator
  fdb-server-1:
    depends_on:
      - fdb-coordinator
    image: foundationdb:6.1.12
    environment:
      FDB_COORDINATOR: fdb-coordinator
  fdb-server-2:
    depends_on:
      - fdb-coordinator
    image: foundationdb:6.1.12
    environment:
      FDB_COORDINATOR: fdb-coordinator

  # Bring up the application so that it depends on the cluster.
  app:
    depends_on:
      - fdb-coordinator
      - fdb-server-1
      - fdb-server-2
    build:
      context: app
    ports:
      - 5000:5000/tcp
    environment:
      FDB_COORDINATOR: fdb-coordinator
