name: PR lint

on:
  pull_request:
    branches:
      - main
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@4ae350ed9a17e62d7cf18c8bd8eec61bdde77feb
        with:
          title-regex: '^(SNOW|FDBCORE)-\d*.*'
          on-failed-regex-fail-action: true
          on-failed-regex-request-changes: false
          on-failed-regex-create-review: false
          on-failed-regex-comment:
            "Please ensure you've prefixed your PR with a SNOW/FDBCORE ticket number."
          repo-token: "${{ secrets.GITHUB_TOKEN }}"